version: '3.8'

services:
  darkdus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: darkdus
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config:/usr/src/app/config
      - ./client/temp:/usr/src/app/client/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3